from django.db import models

# Create your models here.


class Master(models.Model):
    playerID = models.CharField(max_length=10)
    birthYear = models.IntegerField()
    birthMonth = models.IntegerField()
    birthDay = models.IntegerField()
    birthCountry = models.CharField(max_length=50)
    birthState = models.CharField(max_length=5)
    birthCity = models.CharField(max_length=50)
    deathYear = models.IntegerField()
    deathMonth = models.IntegerField()
    deathDay = models.IntegerField()
    deathCountry = models.CharField(max_length=50)
    deathState = models.CharField(max_length=5)
    deathCity = models.CharField(max_length=50)
    nameFirst = models.CharField(max_length=50)
    nameLast = models.CharField(max_length=50)
    nameGiven = models.CharField(max_length=50)
    weight = models.IntegerField()
    height = models.IntegerField()
    bats = models.CharField(max_length=5)
    throws = models.CharField(max_length=5)
    debut = models.CharField(max_length=50)
    finalGame = models.CharField(max_length=50)
    retroID = models.CharField(max_length=10)
    bbrefID = models.CharField(max_length=10)


class Batting(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.IntegerField()
    stint = models.IntegerField()
    teamID = models.CharField(max_length=5)
    lgID = models.CharField(max_length=5)
    G = models.IntegerField()
    AB = models.IntegerField()
    R = models.IntegerField()
    H = models.IntegerField()
    doubles = models.IntegerField()
    triples = models.IntegerField()
    HR = models.IntegerField()
    RBI = models.IntegerField()
    SB = models.IntegerField()
    CS = models.IntegerField()
    BB = models.IntegerField()
    SO = models.IntegerField()
    IBB = models.IntegerField()
    HBP = models.IntegerField()
    SH = models.IntegerField()
    SF = models.IntegerField()
    GIDP = models.IntegerField()


class Pitching(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.IntegerField()
    stint = models.IntegerField()
    teamID = models.CharField(max_length=10)
    lgID = models.CharField(max_length=10)
    W = models.IntegerField()
    L = models.IntegerField()
    G = models.IntegerField()
    GS = models.IntegerField()
    CG = models.IntegerField()
    SHO = models.IntegerField()
    SV = models.IntegerField()
    IPouts = models.IntegerField()
    H = models.IntegerField()
    ER = models.IntegerField()
    HR = models.IntegerField()
    BB = models.IntegerField()
    SO = models.IntegerField()
    BAOpp = models.IntegerField()
    ERA = models.IntegerField()
    IBB = models.IntegerField()
    WP = models.IntegerField()
    HBP = models.IntegerField()
    BK = models.IntegerField()
    BFP = models.IntegerField()
    GF = models.IntegerField()
    R = models.IntegerField()
    SH = models.IntegerField()
    SF = models.IntegerField()
    GIDP = models.IntegerField()


class Fielding(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.IntegerField()
    stint = models.IntegerField()
    teamID = models.CharField(max_length=10)
    lgID = models.CharField(max_length=10)
    POS = models.IntegerField()
    G = models.IntegerField()
    GS = models.IntegerField()
    InnOuts = models.IntegerField()
    PO = models.IntegerField()
    A = models.IntegerField()
    E = models.IntegerField()
    DP = models.IntegerField()
    PB = models.IntegerField()
    WP = models.IntegerField()
    SB = models.IntegerField()
    CS = models.IntegerField()
    ZR = models.IntegerField()
