from django.db import models

# Create your models here.


class Master(models.Model):
    playerID = models.CharField(max_length=10, null=True, blank=True)
    birthYear = models.CharField(max_length=50, null=True, blank=True)
    birthMonth = models.CharField(max_length=50, null=True, blank=True)
    birthDay = models.CharField(max_length=50, null=True, blank=True)
    birthCountry = models.CharField(max_length=50, null=True, blank=True)
    birthState = models.CharField(max_length=5, null=True, blank=True)
    birthCity = models.CharField(max_length=50, null=True, blank=True)
    deathYear = models.CharField(max_length=50, null=True, blank=True)
    deathMonth = models.CharField(max_length=50, null=True, blank=True)
    deathDay = models.CharField(max_length=50, null=True, blank=True)
    deathCountry = models.CharField(max_length=50, null=True, blank=True)
    deathState = models.CharField(max_length=5, null=True, blank=True)
    deathCity = models.CharField(max_length=50, null=True, blank=True)
    nameFirst = models.CharField(max_length=50, null=True, blank=True)
    nameLast = models.CharField(max_length=50, null=True, blank=True)
    nameGiven = models.CharField(max_length=50, null=True, blank=True)
    weight = models.CharField(max_length=50, null=True, blank=True)
    height = models.CharField(max_length=50, null=True, blank=True)
    bats = models.CharField(max_length=5, null=True, blank=True)
    throws = models.CharField(max_length=5, null=True, blank=True)
    debut = models.CharField(max_length=50, null=True, blank=True)
    finalGame = models.CharField(max_length=50, null=True, blank=True)
    retroID = models.CharField(max_length=10, null=True, blank=True)
    bbrefID = models.CharField(max_length=10, null=True, blank=True)


class Batting(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.CharField(max_length=50, null=True, blank=True)
    stint = models.CharField(max_length=50, null=True, blank=True)
    teamID = models.CharField(max_length=5, null=True, blank=True)
    lgID = models.CharField(max_length=5, null=True, blank=True)
    G = models.CharField(max_length=50, null=True, blank=True)
    AB = models.CharField(max_length=50, null=True, blank=True)
    R = models.CharField(max_length=50, null=True, blank=True)
    H = models.CharField(max_length=50, null=True, blank=True)
    doubles = models.CharField(max_length=50, null=True, blank=True)
    triples = models.CharField(max_length=50, null=True, blank=True)
    HR = models.CharField(max_length=50, null=True, blank=True)
    RBI = models.CharField(max_length=50, null=True, blank=True)
    SB = models.CharField(max_length=50, null=True, blank=True)
    CS = models.CharField(max_length=50, null=True, blank=True)
    BB = models.CharField(max_length=50, null=True, blank=True)
    SO = models.CharField(max_length=50, null=True, blank=True)
    IBB = models.CharField(max_length=50, null=True, blank=True)
    HBP = models.CharField(max_length=50, null=True, blank=True)
    SH = models.CharField(max_length=50, null=True, blank=True)
    SF = models.CharField(max_length=50, null=True, blank=True)
    GIDP = models.CharField(max_length=50, null=True, blank=True)


class Pitching(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.CharField(max_length=50, null=True, blank=True)
    stint = models.CharField(max_length=50, null=True, blank=True)
    teamID = models.CharField(max_length=10, null=True, blank=True)
    lgID = models.CharField(max_length=10, null=True, blank=True)
    W = models.CharField(max_length=50, null=True, blank=True)
    L = models.CharField(max_length=50, null=True, blank=True)
    G = models.CharField(max_length=50, null=True, blank=True)
    GS = models.CharField(max_length=50, null=True, blank=True)
    CG = models.CharField(max_length=50, null=True, blank=True)
    SHO = models.CharField(max_length=50, null=True, blank=True)
    SV = models.CharField(max_length=50, null=True, blank=True)
    IPouts = models.CharField(max_length=50, null=True, blank=True)
    H = models.CharField(max_length=50, null=True, blank=True)
    ER = models.CharField(max_length=50, null=True, blank=True)
    HR = models.CharField(max_length=50, null=True, blank=True)
    BB = models.CharField(max_length=50, null=True, blank=True)
    SO = models.CharField(max_length=50, null=True, blank=True)
    BAOpp = models.CharField(max_length=50, null=True, blank=True)
    ERA = models.CharField(max_length=50, null=True, blank=True)
    IBB = models.CharField(max_length=50, null=True, blank=True)
    WP = models.CharField(max_length=50, null=True, blank=True)
    HBP = models.CharField(max_length=50, null=True, blank=True)
    BK = models.CharField(max_length=50, null=True, blank=True)
    BFP = models.CharField(max_length=50, null=True, blank=True)
    GF = models.CharField(max_length=50, null=True, blank=True)
    R = models.CharField(max_length=50, null=True, blank=True)
    SH = models.CharField(max_length=50, null=True, blank=True)
    SF = models.CharField(max_length=50, null=True, blank=True)
    GIDP = models.CharField(max_length=50, null=True, blank=True)


class Fielding(models.Model):
    playerID = models.ForeignKey(Master)
    yearID = models.CharField(max_length=50, null=True, blank=True)
    stint = models.CharField(max_length=50, null=True, blank=True)
    teamID = models.CharField(max_length=10, null=True, blank=True)
    lgID = models.CharField(max_length=10, null=True, blank=True)
    POS = models.CharField(max_length=50, null=True, blank=True)
    G = models.CharField(max_length=50, null=True, blank=True)
    GS = models.CharField(max_length=50, null=True, blank=True)
    InnOuts = models.CharField(max_length=50, null=True, blank=True)
    PO = models.CharField(max_length=50, null=True, blank=True)
    A = models.CharField(max_length=50, null=True, blank=True)
    E = models.CharField(max_length=50, null=True, blank=True)
    DP = models.CharField(max_length=50, null=True, blank=True)
    PB = models.CharField(max_length=50, null=True, blank=True)
    WP = models.CharField(max_length=50, null=True, blank=True)
    SB = models.CharField(max_length=50, null=True, blank=True)
    CS = models.CharField(max_length=50, null=True, blank=True)
    ZR = models.CharField(max_length=50, null=True, blank=True)
